Python
Tribler/document-attestation-service pull request #2
Opened 2019-04-04 18:52 UTC by jonay2000

Added a small python server which both statically serves the dist folder and simultaniously serves 2 ipv8 peers

2019-04-04 18:53 UTC, jonay2000 commented
oh wait

2019-04-04 18:53 UTC, jonay2000 commented
should we merge into the other branch and merge them together into master?

2019-04-05 21:49 UTC, dsluijk commented
I think it's best to merge into `feat/boilerplating` first, then merge into `master`, as this model does not really make sense anymore. After merging to `master` we can start using feature branches

2019-04-05 21:52 UTC, dsluijk requested changes

2019-04-05 21:52 UTC, dsluijk commented on Pipfile.lock
> +{
You could probably delete and ignore this file, as it generates a lot of noise.

2019-04-09 18:34 UTC, dsluijk approved these changes

2019-04-09 18:34 UTC, merged